name: ovavue
description: A tidy budget overview planner.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  intl: ^0.17.0
  logging: ^1.1.1
  meta: ^1.8.0
  package_info_plus: ^3.0.3
  platform: ^3.1.0
  registry:
    git: https://github.com/jogboms/registry.dart.git
  riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  sentry: ^6.15.1
  universal_io: ^2.2.0

dev_dependencies:
  build_runner:
  device_info_plus_platform_interface: ^7.0.0
  flutter_test:
    sdk: flutter
  mfsao: ^3.0.0
  mocktail: ^0.3.0
  package_info_plus_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.1.4
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
  generate: true
