name: Format, Analyze and Test

on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - master
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  default_run:
    name: Format, Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize environment variables from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Install tools
        run: ./tool/install.sh

      - run: flutter doctor
      - run: flutter pub get
      - run: dart format --set-exit-if-changed -l 120 lib
      - run: flutter pub run build_runner build
      - run: flutter analyze lib
      - run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Clean-up lcov
        run: ./tool/clean_coverage.sh

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
